#nullable enable
using System.Runtime.InteropServices;

namespace Larnix.Core.Serialization;

public interface IFixedString
{
    int Capacity { get; }
}

/*
AUTOGEN BEGIN
#SIZE = 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768

[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly record struct FixedString#SIZE : IFixedString
{
    private readonly FixedBuffer#SIZE<char> _buffer;

    public int Capacity => #SIZE / 2;

    public FixedString#SIZE(string value)
    {
        FixedBuffer#SIZE<char> buffer = new();

        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Push(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString#SIZE(string value)
    {
        return new FixedString#SIZE(value);
    }

    public static implicit operator string(in FixedString#SIZE value)
    {
        char[] chars = value._buffer.ToArray();
        return new string(chars);
    }

    public override string ToString() => this;
}
AUTOGEN END
*/

#region Auto-Generated Code

// This code was generated by a simple code generator. Do not modify this section manually.
// Instead, modify the payload between the AUTOGEN BEGIN and AUTOGEN END markers to change the generated code
// and then regenerate the code from the Unity Editor window (Automation/Tools/Regenerate Code).


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly record struct FixedString16 : IFixedString
{
    private readonly FixedBuffer16<char> _buffer;

    public int Capacity => 16 / 2;

    public FixedString16(string value)
    {
        FixedBuffer16<char> buffer = new();

        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Push(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString16(string value)
    {
        return new FixedString16(value);
    }

    public static implicit operator string(in FixedString16 value)
    {
        char[] chars = value._buffer.ToArray();
        return new string(chars);
    }

    public override string ToString() => this;
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly record struct FixedString32 : IFixedString
{
    private readonly FixedBuffer32<char> _buffer;

    public int Capacity => 32 / 2;

    public FixedString32(string value)
    {
        FixedBuffer32<char> buffer = new();

        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Push(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString32(string value)
    {
        return new FixedString32(value);
    }

    public static implicit operator string(in FixedString32 value)
    {
        char[] chars = value._buffer.ToArray();
        return new string(chars);
    }

    public override string ToString() => this;
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly record struct FixedString64 : IFixedString
{
    private readonly FixedBuffer64<char> _buffer;

    public int Capacity => 64 / 2;

    public FixedString64(string value)
    {
        FixedBuffer64<char> buffer = new();

        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Push(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString64(string value)
    {
        return new FixedString64(value);
    }

    public static implicit operator string(in FixedString64 value)
    {
        char[] chars = value._buffer.ToArray();
        return new string(chars);
    }

    public override string ToString() => this;
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly record struct FixedString128 : IFixedString
{
    private readonly FixedBuffer128<char> _buffer;

    public int Capacity => 128 / 2;

    public FixedString128(string value)
    {
        FixedBuffer128<char> buffer = new();

        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Push(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString128(string value)
    {
        return new FixedString128(value);
    }

    public static implicit operator string(in FixedString128 value)
    {
        char[] chars = value._buffer.ToArray();
        return new string(chars);
    }

    public override string ToString() => this;
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly record struct FixedString256 : IFixedString
{
    private readonly FixedBuffer256<char> _buffer;

    public int Capacity => 256 / 2;

    public FixedString256(string value)
    {
        FixedBuffer256<char> buffer = new();

        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Push(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString256(string value)
    {
        return new FixedString256(value);
    }

    public static implicit operator string(in FixedString256 value)
    {
        char[] chars = value._buffer.ToArray();
        return new string(chars);
    }

    public override string ToString() => this;
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly record struct FixedString512 : IFixedString
{
    private readonly FixedBuffer512<char> _buffer;

    public int Capacity => 512 / 2;

    public FixedString512(string value)
    {
        FixedBuffer512<char> buffer = new();

        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Push(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString512(string value)
    {
        return new FixedString512(value);
    }

    public static implicit operator string(in FixedString512 value)
    {
        char[] chars = value._buffer.ToArray();
        return new string(chars);
    }

    public override string ToString() => this;
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly record struct FixedString1024 : IFixedString
{
    private readonly FixedBuffer1024<char> _buffer;

    public int Capacity => 1024 / 2;

    public FixedString1024(string value)
    {
        FixedBuffer1024<char> buffer = new();

        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Push(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString1024(string value)
    {
        return new FixedString1024(value);
    }

    public static implicit operator string(in FixedString1024 value)
    {
        char[] chars = value._buffer.ToArray();
        return new string(chars);
    }

    public override string ToString() => this;
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly record struct FixedString2048 : IFixedString
{
    private readonly FixedBuffer2048<char> _buffer;

    public int Capacity => 2048 / 2;

    public FixedString2048(string value)
    {
        FixedBuffer2048<char> buffer = new();

        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Push(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString2048(string value)
    {
        return new FixedString2048(value);
    }

    public static implicit operator string(in FixedString2048 value)
    {
        char[] chars = value._buffer.ToArray();
        return new string(chars);
    }

    public override string ToString() => this;
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly record struct FixedString4096 : IFixedString
{
    private readonly FixedBuffer4096<char> _buffer;

    public int Capacity => 4096 / 2;

    public FixedString4096(string value)
    {
        FixedBuffer4096<char> buffer = new();

        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Push(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString4096(string value)
    {
        return new FixedString4096(value);
    }

    public static implicit operator string(in FixedString4096 value)
    {
        char[] chars = value._buffer.ToArray();
        return new string(chars);
    }

    public override string ToString() => this;
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly record struct FixedString8192 : IFixedString
{
    private readonly FixedBuffer8192<char> _buffer;

    public int Capacity => 8192 / 2;

    public FixedString8192(string value)
    {
        FixedBuffer8192<char> buffer = new();

        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Push(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString8192(string value)
    {
        return new FixedString8192(value);
    }

    public static implicit operator string(in FixedString8192 value)
    {
        char[] chars = value._buffer.ToArray();
        return new string(chars);
    }

    public override string ToString() => this;
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly record struct FixedString16384 : IFixedString
{
    private readonly FixedBuffer16384<char> _buffer;

    public int Capacity => 16384 / 2;

    public FixedString16384(string value)
    {
        FixedBuffer16384<char> buffer = new();

        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Push(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString16384(string value)
    {
        return new FixedString16384(value);
    }

    public static implicit operator string(in FixedString16384 value)
    {
        char[] chars = value._buffer.ToArray();
        return new string(chars);
    }

    public override string ToString() => this;
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly record struct FixedString32768 : IFixedString
{
    private readonly FixedBuffer32768<char> _buffer;

    public int Capacity => 32768 / 2;

    public FixedString32768(string value)
    {
        FixedBuffer32768<char> buffer = new();

        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Push(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString32768(string value)
    {
        return new FixedString32768(value);
    }

    public static implicit operator string(in FixedString32768 value)
    {
        char[] chars = value._buffer.ToArray();
        return new string(chars);
    }

    public override string ToString() => this;
}

#endregion