#nullable enable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Larnix.Core.Serialization;

public interface IFixedBuffer<T> where T : unmanaged
{
    int Count { get; }
    int Capacity { get; }
    bool IsFull { get; }

    T At(int index);
    void Add(in T value);
    void AddRange(ReadOnlySpan<T> values);
    void ReadInto(Span<T> target);
    T[] ToArray(); // allocates!

    void Clear();
}

/*
AUTOGEN BEGIN
#SIZE = 8 16 32 64 128 256 512 1024

[StructLayout(LayoutKind.Sequential, Pack = 1)]
public unsafe struct FixedBuffer#SIZE<T> : IFixedBuffer<T>, ISanitizable<FixedBuffer#SIZE<T>> where T : unmanaged
{
    private ushort _count;
    private fixed byte _buffer[#SIZE];

    public readonly int Count => Math.Min(_count, Capacity);
    public readonly int Capacity => (ushort)(#SIZE / sizeof(T));
    public readonly bool IsFull => Count == Capacity;

    static FixedBuffer#SIZE()
    {
        _ = Binary<T>.Size; // throw exception instantly when trying to use with an incompatible type
    }

    public readonly T At(int index)
    {
        if (index < 0 || index >= Count)
        {
            throw new ArgumentOutOfRangeException(nameof(index), $"Cannot access element with index {index}.");
        }

        fixed (byte* ptr = _buffer)
        {
            return Unsafe.ReadUnaligned<T>(ref ptr[index * sizeof(T)]);
        }
    }

    public void Add(in T value)
    {
        if (IsFull)
        {
            throw new InvalidOperationException($"Fixed buffer is full.");
        }

        fixed (byte* ptr = _buffer)
        {
            Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], Serializer.Filter(value));
            _count++;
        }
    }

    public void AddRange(ReadOnlySpan<T> values)
    {
        if (Count + values.Length > Capacity)
        {
            throw new InvalidOperationException($"Not enough capacity to add range to a fixed buffer.");
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < values.Length; i++)
            {
                Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], Serializer.Filter(values[i]));
                _count++;
            }
        }
    }

    public readonly void ReadInto(Span<T> target)
    {
        if (target.Length != Count)
        {
            throw new ArgumentException($"Target span length must be equal to the number of elements in the fixed buffer.", nameof(target));
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < Count; i++)
            {
                target[i] = Unsafe.ReadUnaligned<T>(ref ptr[i * sizeof(T)]);
            }
        }
    }

    public readonly T[] ToArray()
    {
        Span<T> buffer = stackalloc T[Count];
        ReadInto(buffer);
        return buffer.ToArray();
    }

    public void Clear()
    {
        this = default;
    }

    public readonly FixedBuffer#SIZE<T> Sanitize()
    {
        FixedBuffer#SIZE<T> sanitized = new();
        for (int i = 0; i < Count; i++)
        {
            T filtered = Sanitizer.Filter(At(i));
            sanitized.Add(filtered);
        }
        return sanitized;
    }
}

AUTOGEN END
*/

#region Auto-Generated Code

// This code was generated by a simple code generator. Do not modify this section manually.
// Instead, modify the payload between the AUTOGEN BEGIN and AUTOGEN END markers to change the generated code
// and then regenerate the code from the Unity Editor window (Automation/Tools/Regenerate Code).

[StructLayout(LayoutKind.Sequential, Pack = 1)]
public unsafe struct FixedBuffer8<T> : IFixedBuffer<T>, ISanitizable<FixedBuffer8<T>> where T : unmanaged
{
    private ushort _count;
    private fixed byte _buffer[8];

    public readonly int Count => Math.Min(_count, Capacity);
    public readonly int Capacity => (ushort)(8 / sizeof(T));
    public readonly bool IsFull => Count == Capacity;

    static FixedBuffer8()
    {
        _ = Binary<T>.Size;
    }

    public readonly T At(int index)
    {
        if (index < 0 || index >= Count)
        {
            throw new ArgumentOutOfRangeException(nameof(index), $"Cannot access element with index {index}.");
        }

        fixed (byte* ptr = _buffer)
        {
            return Unsafe.ReadUnaligned<T>(ref ptr[index * sizeof(T)]);
        }
    }

    public void Add(in T value)
    {
        if (IsFull)
        {
            throw new InvalidOperationException($"Fixed buffer is full.");
        }

        fixed (byte* ptr = _buffer)
        {
            Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], value);
            _count++;
        }
    }

    public void AddRange(ReadOnlySpan<T> values)
    {
        if (Count + values.Length > Capacity)
        {
            throw new InvalidOperationException($"Not enough capacity to add range to a fixed buffer.");
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < values.Length; i++)
            {
                Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], values[i]);
                _count++;
            }
        }
    }

    public readonly void ReadInto(Span<T> target)
    {
        if (target.Length != Count)
        {
            throw new ArgumentException($"Target span length must be equal to the number of elements in the fixed buffer.", nameof(target));
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < Count; i++)
            {
                target[i] = Unsafe.ReadUnaligned<T>(ref ptr[i * sizeof(T)]);
            }
        }
    }

    public readonly T[] ToArray()
    {
        Span<T> buffer = stackalloc T[Count];
        ReadInto(buffer);
        return buffer.ToArray();
    }

    public void Clear()
    {
        this = default;
    }

    public readonly FixedBuffer8<T> Sanitize()
    {
        FixedBuffer8<T> sanitized = new();
        for (int i = 0; i<Count; i++)
        {
            T filtered = Sanitizer.Filter(At(i));
            sanitized.Add(filtered);
        }
        return sanitized;
    }
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public unsafe struct FixedBuffer16<T> : IFixedBuffer<T>, ISanitizable<FixedBuffer16<T>> where T : unmanaged
{
    private ushort _count;
    private fixed byte _buffer[16];

    public readonly int Count => Math.Min(_count, Capacity);
    public readonly int Capacity => (ushort)(16 / sizeof(T));
    public readonly bool IsFull => Count == Capacity;

    static FixedBuffer16()
    {
        _ = Binary<T>.Size;
    }

    public readonly T At(int index)
    {
        if (index < 0 || index >= Count)
        {
            throw new ArgumentOutOfRangeException(nameof(index), $"Cannot access element with index {index}.");
        }

        fixed (byte* ptr = _buffer)
        {
            return Unsafe.ReadUnaligned<T>(ref ptr[index * sizeof(T)]);
        }
    }

    public void Add(in T value)
    {
        if (IsFull)
        {
            throw new InvalidOperationException($"Fixed buffer is full.");
        }

        fixed (byte* ptr = _buffer)
        {
            Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], value);
            _count++;
        }
    }

    public void AddRange(ReadOnlySpan<T> values)
    {
        if (Count + values.Length > Capacity)
        {
            throw new InvalidOperationException($"Not enough capacity to add range to a fixed buffer.");
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < values.Length; i++)
            {
                Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], values[i]);
                _count++;
            }
        }
    }

    public readonly void ReadInto(Span<T> target)
    {
        if (target.Length != Count)
        {
            throw new ArgumentException($"Target span length must be equal to the number of elements in the fixed buffer.", nameof(target));
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < Count; i++)
            {
                target[i] = Unsafe.ReadUnaligned<T>(ref ptr[i * sizeof(T)]);
            }
        }
    }

    public readonly T[] ToArray()
    {
        Span<T> buffer = stackalloc T[Count];
        ReadInto(buffer);
        return buffer.ToArray();
    }

    public void Clear()
    {
        this = default;
    }

    public readonly FixedBuffer16<T> Sanitize()
    {
        FixedBuffer16<T> sanitized = new();
        for (int i = 0; i < Count; i++)
        {
            T filtered = Sanitizer.Filter(At(i));
            sanitized.Add(filtered);
        }
        return sanitized;
    }
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public unsafe struct FixedBuffer32<T> : IFixedBuffer<T>, ISanitizable<FixedBuffer32<T>> where T : unmanaged
{
    private ushort _count;
    private fixed byte _buffer[32];

    public readonly int Count => Math.Min(_count, Capacity);
    public readonly int Capacity => (ushort)(32 / sizeof(T));
    public readonly bool IsFull => Count == Capacity;

    static FixedBuffer32()
    {
        _ = Binary<T>.Size;
    }

    public readonly T At(int index)
    {
        if (index < 0 || index >= Count)
        {
            throw new ArgumentOutOfRangeException(nameof(index), $"Cannot access element with index {index}.");
        }

        fixed (byte* ptr = _buffer)
        {
            return Unsafe.ReadUnaligned<T>(ref ptr[index * sizeof(T)]);
        }
    }

    public void Add(in T value)
    {
        if (IsFull)
        {
            throw new InvalidOperationException($"Fixed buffer is full.");
        }

        fixed (byte* ptr = _buffer)
        {
            Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], value);
            _count++;
        }
    }

    public void AddRange(ReadOnlySpan<T> values)
    {
        if (Count + values.Length > Capacity)
        {
            throw new InvalidOperationException($"Not enough capacity to add range to a fixed buffer.");
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < values.Length; i++)
            {
                Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], values[i]);
                _count++;
            }
        }
    }

    public readonly void ReadInto(Span<T> target)
    {
        if (target.Length != Count)
        {
            throw new ArgumentException($"Target span length must be equal to the number of elements in the fixed buffer.", nameof(target));
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < Count; i++)
            {
                target[i] = Unsafe.ReadUnaligned<T>(ref ptr[i * sizeof(T)]);
            }
        }
    }

    public readonly T[] ToArray()
    {
        Span<T> buffer = stackalloc T[Count];
        ReadInto(buffer);
        return buffer.ToArray();
    }

    public void Clear()
    {
        this = default;
    }

    public readonly FixedBuffer32<T> Sanitize()
    {
        FixedBuffer32<T> sanitized = new();
        for (int i = 0; i < Count; i++)
        {
            T filtered = Sanitizer.Filter(At(i));
            sanitized.Add(filtered);
        }
        return sanitized;
    }
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public unsafe struct FixedBuffer64<T> : IFixedBuffer<T>, ISanitizable<FixedBuffer64<T>> where T : unmanaged
{
    private ushort _count;
    private fixed byte _buffer[64];

    public readonly int Count => Math.Min(_count, Capacity);
    public readonly int Capacity => (ushort)(64 / sizeof(T));
    public readonly bool IsFull => Count == Capacity;

    static FixedBuffer64()
    {
        _ = Binary<T>.Size;
    }

    public readonly T At(int index)
    {
        if (index < 0 || index >= Count)
        {
            throw new ArgumentOutOfRangeException(nameof(index), $"Cannot access element with index {index}.");
        }

        fixed (byte* ptr = _buffer)
        {
            return Unsafe.ReadUnaligned<T>(ref ptr[index * sizeof(T)]);
        }
    }

    public void Add(in T value)
    {
        if (IsFull)
        {
            throw new InvalidOperationException($"Fixed buffer is full.");
        }

        fixed (byte* ptr = _buffer)
        {
            Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], value);
            _count++;
        }
    }

    public void AddRange(ReadOnlySpan<T> values)
    {
        if (Count + values.Length > Capacity)
        {
            throw new InvalidOperationException($"Not enough capacity to add range to a fixed buffer.");
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < values.Length; i++)
            {
                Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], values[i]);
                _count++;
            }
        }
    }

    public readonly void ReadInto(Span<T> target)
    {
        if (target.Length != Count)
        {
            throw new ArgumentException($"Target span length must be equal to the number of elements in the fixed buffer.", nameof(target));
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < Count; i++)
            {
                target[i] = Unsafe.ReadUnaligned<T>(ref ptr[i * sizeof(T)]);
            }
        }
    }

    public readonly T[] ToArray()
    {
        Span<T> buffer = stackalloc T[Count];
        ReadInto(buffer);
        return buffer.ToArray();
    }

    public void Clear()
    {
        this = default;
    }

    public readonly FixedBuffer64<T> Sanitize()
    {
        FixedBuffer64<T> sanitized = new();
        for (int i = 0; i < Count; i++)
        {
            T filtered = Sanitizer.Filter(At(i));
            sanitized.Add(filtered);
        }
        return sanitized;
    }
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public unsafe struct FixedBuffer128<T> : IFixedBuffer<T>, ISanitizable<FixedBuffer128<T>> where T : unmanaged
{
    private ushort _count;
    private fixed byte _buffer[128];

    public readonly int Count => Math.Min(_count, Capacity);
    public readonly int Capacity => (ushort)(128 / sizeof(T));
    public readonly bool IsFull => Count == Capacity;

    static FixedBuffer128()
    {
        _ = Binary<T>.Size;
    }

    public readonly T At(int index)
    {
        if (index < 0 || index >= Count)
        {
            throw new ArgumentOutOfRangeException(nameof(index), $"Cannot access element with index {index}.");
        }

        fixed (byte* ptr = _buffer)
        {
            return Unsafe.ReadUnaligned<T>(ref ptr[index * sizeof(T)]);
        }
    }

    public void Add(in T value)
    {
        if (IsFull)
        {
            throw new InvalidOperationException($"Fixed buffer is full.");
        }

        fixed (byte* ptr = _buffer)
        {
            Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], value);
            _count++;
        }
    }

    public void AddRange(ReadOnlySpan<T> values)
    {
        if (Count + values.Length > Capacity)
        {
            throw new InvalidOperationException($"Not enough capacity to add range to a fixed buffer.");
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < values.Length; i++)
            {
                Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], values[i]);
                _count++;
            }
        }
    }

    public readonly void ReadInto(Span<T> target)
    {
        if (target.Length != Count)
        {
            throw new ArgumentException($"Target span length must be equal to the number of elements in the fixed buffer.", nameof(target));
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < Count; i++)
            {
                target[i] = Unsafe.ReadUnaligned<T>(ref ptr[i * sizeof(T)]);
            }
        }
    }

    public readonly T[] ToArray()
    {
        Span<T> buffer = stackalloc T[Count];
        ReadInto(buffer);
        return buffer.ToArray();
    }

    public void Clear()
    {
        this = default;
    }

    public readonly FixedBuffer128<T> Sanitize()
    {
        FixedBuffer128<T> sanitized = new();
        for (int i = 0; i < Count; i++)
        {
            T filtered = Sanitizer.Filter(At(i));
            sanitized.Add(filtered);
        }
        return sanitized;
    }
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public unsafe struct FixedBuffer256<T> : IFixedBuffer<T>, ISanitizable<FixedBuffer256<T>> where T : unmanaged
{
    private ushort _count;
    private fixed byte _buffer[256];

    public readonly int Count => Math.Min(_count, Capacity);
    public readonly int Capacity => (ushort)(256 / sizeof(T));
    public readonly bool IsFull => Count == Capacity;

    static FixedBuffer256()
    {
        _ = Binary<T>.Size;
    }

    public readonly T At(int index)
    {
        if (index < 0 || index >= Count)
        {
            throw new ArgumentOutOfRangeException(nameof(index), $"Cannot access element with index {index}.");
        }

        fixed (byte* ptr = _buffer)
        {
            return Unsafe.ReadUnaligned<T>(ref ptr[index * sizeof(T)]);
        }
    }

    public void Add(in T value)
    {
        if (IsFull)
        {
            throw new InvalidOperationException($"Fixed buffer is full.");
        }

        fixed (byte* ptr = _buffer)
        {
            Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], value);
            _count++;
        }
    }

    public void AddRange(ReadOnlySpan<T> values)
    {
        if (Count + values.Length > Capacity)
        {
            throw new InvalidOperationException($"Not enough capacity to add range to a fixed buffer.");
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < values.Length; i++)
            {
                Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], values[i]);
                _count++;
            }
        }
    }

    public readonly void ReadInto(Span<T> target)
    {
        if (target.Length != Count)
        {
            throw new ArgumentException($"Target span length must be equal to the number of elements in the fixed buffer.", nameof(target));
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < Count; i++)
            {
                target[i] = Unsafe.ReadUnaligned<T>(ref ptr[i * sizeof(T)]);
            }
        }
    }

    public readonly T[] ToArray()
    {
        Span<T> buffer = stackalloc T[Count];
        ReadInto(buffer);
        return buffer.ToArray();
    }

    public void Clear()
    {
        this = default;
    }

    public readonly FixedBuffer256<T> Sanitize()
    {
        FixedBuffer256<T> sanitized = new();
        for (int i = 0; i < Count; i++)
        {
            T filtered = Sanitizer.Filter(At(i));
            sanitized.Add(filtered);
        }
        return sanitized;
    }
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public unsafe struct FixedBuffer512<T> : IFixedBuffer<T>, ISanitizable<FixedBuffer512<T>> where T : unmanaged
{
    private ushort _count;
    private fixed byte _buffer[512];

    public readonly int Count => Math.Min(_count, Capacity);
    public readonly int Capacity => (ushort)(512 / sizeof(T));
    public readonly bool IsFull => Count == Capacity;

    static FixedBuffer512()
    {
        _ = Binary<T>.Size;
    }

    public readonly T At(int index)
    {
        if (index < 0 || index >= Count)
        {
            throw new ArgumentOutOfRangeException(nameof(index), $"Cannot access element with index {index}.");
        }

        fixed (byte* ptr = _buffer)
        {
            return Unsafe.ReadUnaligned<T>(ref ptr[index * sizeof(T)]);
        }
    }

    public void Add(in T value)
    {
        if (IsFull)
        {
            throw new InvalidOperationException($"Fixed buffer is full.");
        }

        fixed (byte* ptr = _buffer)
        {
            Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], value);
            _count++;
        }
    }

    public void AddRange(ReadOnlySpan<T> values)
    {
        if (Count + values.Length > Capacity)
        {
            throw new InvalidOperationException($"Not enough capacity to add range to a fixed buffer.");
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < values.Length; i++)
            {
                Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], values[i]);
                _count++;
            }
        }
    }

    public readonly void ReadInto(Span<T> target)
    {
        if (target.Length != Count)
        {
            throw new ArgumentException($"Target span length must be equal to the number of elements in the fixed buffer.", nameof(target));
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < Count; i++)
            {
                target[i] = Unsafe.ReadUnaligned<T>(ref ptr[i * sizeof(T)]);
            }
        }
    }

    public readonly T[] ToArray()
    {
        Span<T> buffer = stackalloc T[Count];
        ReadInto(buffer);
        return buffer.ToArray();
    }

    public void Clear()
    {
        this = default;
    }

    public readonly FixedBuffer512<T> Sanitize()
    {
        FixedBuffer512<T> sanitized = new();
        for (int i = 0; i < Count; i++)
        {
            T filtered = Sanitizer.Filter(At(i));
            sanitized.Add(filtered);
        }
        return sanitized;
    }
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public unsafe struct FixedBuffer1024<T> : IFixedBuffer<T>, ISanitizable<FixedBuffer1024<T>> where T : unmanaged
{
    private ushort _count;
    private fixed byte _buffer[1024];

    public readonly int Count => Math.Min(_count, Capacity);
    public readonly int Capacity => (ushort)(1024 / sizeof(T));
    public readonly bool IsFull => Count == Capacity;

    static FixedBuffer1024()
    {
        _ = Binary<T>.Size;
    }

    public readonly T At(int index)
    {
        if (index < 0 || index >= Count)
        {
            throw new ArgumentOutOfRangeException(nameof(index), $"Cannot access element with index {index}.");
        }

        fixed (byte* ptr = _buffer)
        {
            return Unsafe.ReadUnaligned<T>(ref ptr[index * sizeof(T)]);
        }
    }

    public void Add(in T value)
    {
        if (IsFull)
        {
            throw new InvalidOperationException($"Fixed buffer is full.");
        }

        fixed (byte* ptr = _buffer)
        {
            Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], value);
            _count++;
        }
    }

    public void AddRange(ReadOnlySpan<T> values)
    {
        if (Count + values.Length > Capacity)
        {
            throw new InvalidOperationException($"Not enough capacity to add range to a fixed buffer.");
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < values.Length; i++)
            {
                Unsafe.WriteUnaligned(ref ptr[Count * sizeof(T)], values[i]);
                _count++;
            }
        }
    }

    public readonly void ReadInto(Span<T> target)
    {
        if (target.Length != Count)
        {
            throw new ArgumentException($"Target span length must be equal to the number of elements in the fixed buffer.", nameof(target));
        }

        fixed (byte* ptr = _buffer)
        {
            for (int i = 0; i < Count; i++)
            {
                target[i] = Unsafe.ReadUnaligned<T>(ref ptr[i * sizeof(T)]);
            }
        }
    }

    public readonly T[] ToArray()
    {
        Span<T> buffer = stackalloc T[Count];
        ReadInto(buffer);
        return buffer.ToArray();
    }

    public void Clear()
    {
        this = default;
    }

    public readonly FixedBuffer1024<T> Sanitize()
    {
        FixedBuffer1024<T> sanitized = new();
        for (int i = 0; i < Count; i++)
        {
            T filtered = Sanitizer.Filter(At(i));
            sanitized.Add(filtered);
        }
        return sanitized;
    }
}

#endregion