#nullable enable
using System;
using System.Runtime.InteropServices;

namespace Larnix.Core.Serialization;

public interface IFixedString
{
    int Capacity { get; }
    int Length { get; }
}

/*
AUTOGEN BEGIN
#SIZE = 8 16 32 64 128 256 512 1024

[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly struct FixedString#SIZE : IFixedString, IEquatable<FixedString#SIZE>
{
    private readonly FixedBuffer#SIZE<char> _buffer;

    public int Capacity => #SIZE / 2;
    public int Length => _buffer.Count;

    public FixedString#SIZE(string value)
    {
        FixedBuffer#SIZE<char> buffer = new();
        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Add(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString#SIZE(string value)
    {
        return new FixedString#SIZE(value);
    }

    public static implicit operator string(in FixedString#SIZE value)
    {
        Span<char> chars = stackalloc char[value._buffer.Count];
        value._buffer.ReadInto(chars);

        return new string(chars);
    }

    public override string ToString() => this;

    public bool Equals(FixedString#SIZE other)
    {
        Span<char> chars1 = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars1);

        Span<char> chars2 = stackalloc char[other._buffer.Count];
        other._buffer.ReadInto(chars2);

        return chars1.SequenceEqual(chars2);
    }

    public override bool Equals(object? obj)
    {
        return obj is FixedString#SIZE other && Equals(other);
    }

    public override int GetHashCode()
    {
        Span<char> chars = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars);

        HashCode hashcode = new();

        hashcode.Add(chars.Length);
        foreach (char c in chars)
        {
            hashcode.Add(c);
        }

        return hashcode.ToHashCode();
    }

    public static bool operator ==(in FixedString#SIZE left, in FixedString#SIZE right) => left.Equals(right);
    public static bool operator !=(in FixedString#SIZE left, in FixedString#SIZE right) => !left.Equals(right);
}

AUTOGEN END
*/

#region Auto-Generated Code

// This code was generated by a simple code generator. Do not modify this section manually.
// Instead, modify the payload between the AUTOGEN BEGIN and AUTOGEN END markers to change the generated code
// and then regenerate the code from the Unity Editor window (Automation/Tools/Regenerate Code).


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly struct FixedString8 : IFixedString, IEquatable<FixedString8>
{
    private readonly FixedBuffer8<char> _buffer;

    public int Capacity => 8 / 2;
    public int Length => _buffer.Count;

    public FixedString8(string value)
    {
        FixedBuffer8<char> buffer = new();
        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Add(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString8(string value)
    {
        return new FixedString8(value);
    }

    public static implicit operator string(in FixedString8 value)
    {
        Span<char> chars = stackalloc char[value._buffer.Count];
        value._buffer.ReadInto(chars);

        return new string(chars);
    }

    public override string ToString() => this;

    public bool Equals(FixedString8 other)
    {
        Span<char> chars1 = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars1);

        Span<char> chars2 = stackalloc char[other._buffer.Count];
        other._buffer.ReadInto(chars2);

        return chars1.SequenceEqual(chars2);
    }

    public override bool Equals(object? obj)
    {
        return obj is FixedString8 other && Equals(other);
    }

    public override int GetHashCode()
    {
        Span<char> chars = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars);

        HashCode hashcode = new();

        hashcode.Add(chars.Length);
        foreach (char c in chars)
        {
            hashcode.Add(c);
        }

        return hashcode.ToHashCode();
    }

    public static bool operator ==(in FixedString8 left, in FixedString8 right) => left.Equals(right);
    public static bool operator !=(in FixedString8 left, in FixedString8 right) => !left.Equals(right);
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly struct FixedString16 : IFixedString, IEquatable<FixedString16>
{
    private readonly FixedBuffer16<char> _buffer;

    public int Capacity => 16 / 2;
    public int Length => _buffer.Count;

    public FixedString16(string value)
    {
        FixedBuffer16<char> buffer = new();
        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Add(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString16(string value)
    {
        return new FixedString16(value);
    }

    public static implicit operator string(in FixedString16 value)
    {
        Span<char> chars = stackalloc char[value._buffer.Count];
        value._buffer.ReadInto(chars);

        return new string(chars);
    }

    public override string ToString() => this;

    public bool Equals(FixedString16 other)
    {
        Span<char> chars1 = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars1);

        Span<char> chars2 = stackalloc char[other._buffer.Count];
        other._buffer.ReadInto(chars2);

        return chars1.SequenceEqual(chars2);
    }

    public override bool Equals(object? obj)
    {
        return obj is FixedString16 other && Equals(other);
    }

    public override int GetHashCode()
    {
        Span<char> chars = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars);

        HashCode hashcode = new();

        hashcode.Add(chars.Length);
        foreach (char c in chars)
        {
            hashcode.Add(c);
        }

        return hashcode.ToHashCode();
    }

    public static bool operator ==(in FixedString16 left, in FixedString16 right) => left.Equals(right);
    public static bool operator !=(in FixedString16 left, in FixedString16 right) => !left.Equals(right);
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly struct FixedString32 : IFixedString, IEquatable<FixedString32>
{
    private readonly FixedBuffer32<char> _buffer;

    public int Capacity => 32 / 2;
    public int Length => _buffer.Count;

    public FixedString32(string value)
    {
        FixedBuffer32<char> buffer = new();
        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Add(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString32(string value)
    {
        return new FixedString32(value);
    }

    public static implicit operator string(in FixedString32 value)
    {
        Span<char> chars = stackalloc char[value._buffer.Count];
        value._buffer.ReadInto(chars);

        return new string(chars);
    }

    public override string ToString() => this;

    public bool Equals(FixedString32 other)
    {
        Span<char> chars1 = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars1);

        Span<char> chars2 = stackalloc char[other._buffer.Count];
        other._buffer.ReadInto(chars2);

        return chars1.SequenceEqual(chars2);
    }

    public override bool Equals(object? obj)
    {
        return obj is FixedString32 other && Equals(other);
    }

    public override int GetHashCode()
    {
        Span<char> chars = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars);

        HashCode hashcode = new();

        hashcode.Add(chars.Length);
        foreach (char c in chars)
        {
            hashcode.Add(c);
        }

        return hashcode.ToHashCode();
    }

    public static bool operator ==(in FixedString32 left, in FixedString32 right) => left.Equals(right);
    public static bool operator !=(in FixedString32 left, in FixedString32 right) => !left.Equals(right);
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly struct FixedString64 : IFixedString, IEquatable<FixedString64>
{
    private readonly FixedBuffer64<char> _buffer;

    public int Capacity => 64 / 2;
    public int Length => _buffer.Count;

    public FixedString64(string value)
    {
        FixedBuffer64<char> buffer = new();
        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Add(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString64(string value)
    {
        return new FixedString64(value);
    }

    public static implicit operator string(in FixedString64 value)
    {
        Span<char> chars = stackalloc char[value._buffer.Count];
        value._buffer.ReadInto(chars);

        return new string(chars);
    }

    public override string ToString() => this;

    public bool Equals(FixedString64 other)
    {
        Span<char> chars1 = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars1);

        Span<char> chars2 = stackalloc char[other._buffer.Count];
        other._buffer.ReadInto(chars2);

        return chars1.SequenceEqual(chars2);
    }

    public override bool Equals(object? obj)
    {
        return obj is FixedString64 other && Equals(other);
    }

    public override int GetHashCode()
    {
        Span<char> chars = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars);

        HashCode hashcode = new();

        hashcode.Add(chars.Length);
        foreach (char c in chars)
        {
            hashcode.Add(c);
        }

        return hashcode.ToHashCode();
    }

    public static bool operator ==(in FixedString64 left, in FixedString64 right) => left.Equals(right);
    public static bool operator !=(in FixedString64 left, in FixedString64 right) => !left.Equals(right);
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly struct FixedString128 : IFixedString, IEquatable<FixedString128>
{
    private readonly FixedBuffer128<char> _buffer;

    public int Capacity => 128 / 2;
    public int Length => _buffer.Count;

    public FixedString128(string value)
    {
        FixedBuffer128<char> buffer = new();
        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Add(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString128(string value)
    {
        return new FixedString128(value);
    }

    public static implicit operator string(in FixedString128 value)
    {
        Span<char> chars = stackalloc char[value._buffer.Count];
        value._buffer.ReadInto(chars);

        return new string(chars);
    }

    public override string ToString() => this;

    public bool Equals(FixedString128 other)
    {
        Span<char> chars1 = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars1);

        Span<char> chars2 = stackalloc char[other._buffer.Count];
        other._buffer.ReadInto(chars2);

        return chars1.SequenceEqual(chars2);
    }

    public override bool Equals(object? obj)
    {
        return obj is FixedString128 other && Equals(other);
    }

    public override int GetHashCode()
    {
        Span<char> chars = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars);

        HashCode hashcode = new();

        hashcode.Add(chars.Length);
        foreach (char c in chars)
        {
            hashcode.Add(c);
        }

        return hashcode.ToHashCode();
    }

    public static bool operator ==(in FixedString128 left, in FixedString128 right) => left.Equals(right);
    public static bool operator !=(in FixedString128 left, in FixedString128 right) => !left.Equals(right);
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly struct FixedString256 : IFixedString, IEquatable<FixedString256>
{
    private readonly FixedBuffer256<char> _buffer;

    public int Capacity => 256 / 2;
    public int Length => _buffer.Count;

    public FixedString256(string value)
    {
        FixedBuffer256<char> buffer = new();
        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Add(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString256(string value)
    {
        return new FixedString256(value);
    }

    public static implicit operator string(in FixedString256 value)
    {
        Span<char> chars = stackalloc char[value._buffer.Count];
        value._buffer.ReadInto(chars);

        return new string(chars);
    }

    public override string ToString() => this;

    public bool Equals(FixedString256 other)
    {
        Span<char> chars1 = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars1);

        Span<char> chars2 = stackalloc char[other._buffer.Count];
        other._buffer.ReadInto(chars2);

        return chars1.SequenceEqual(chars2);
    }

    public override bool Equals(object? obj)
    {
        return obj is FixedString256 other && Equals(other);
    }

    public override int GetHashCode()
    {
        Span<char> chars = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars);

        HashCode hashcode = new();

        hashcode.Add(chars.Length);
        foreach (char c in chars)
        {
            hashcode.Add(c);
        }

        return hashcode.ToHashCode();
    }

    public static bool operator ==(in FixedString256 left, in FixedString256 right) => left.Equals(right);
    public static bool operator !=(in FixedString256 left, in FixedString256 right) => !left.Equals(right);
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly struct FixedString512 : IFixedString, IEquatable<FixedString512>
{
    private readonly FixedBuffer512<char> _buffer;

    public int Capacity => 512 / 2;
    public int Length => _buffer.Count;

    public FixedString512(string value)
    {
        FixedBuffer512<char> buffer = new();
        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Add(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString512(string value)
    {
        return new FixedString512(value);
    }

    public static implicit operator string(in FixedString512 value)
    {
        Span<char> chars = stackalloc char[value._buffer.Count];
        value._buffer.ReadInto(chars);

        return new string(chars);
    }

    public override string ToString() => this;

    public bool Equals(FixedString512 other)
    {
        Span<char> chars1 = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars1);

        Span<char> chars2 = stackalloc char[other._buffer.Count];
        other._buffer.ReadInto(chars2);

        return chars1.SequenceEqual(chars2);
    }

    public override bool Equals(object? obj)
    {
        return obj is FixedString512 other && Equals(other);
    }

    public override int GetHashCode()
    {
        Span<char> chars = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars);

        HashCode hashcode = new();

        hashcode.Add(chars.Length);
        foreach (char c in chars)
        {
            hashcode.Add(c);
        }

        return hashcode.ToHashCode();
    }

    public static bool operator ==(in FixedString512 left, in FixedString512 right) => left.Equals(right);
    public static bool operator !=(in FixedString512 left, in FixedString512 right) => !left.Equals(right);
}


[StructLayout(LayoutKind.Sequential, Pack = 1)]
public readonly struct FixedString1024 : IFixedString, IEquatable<FixedString1024>
{
    private readonly FixedBuffer1024<char> _buffer;

    public int Capacity => 1024 / 2;
    public int Length => _buffer.Count;

    public FixedString1024(string value)
    {
        FixedBuffer1024<char> buffer = new();
        int lngt = value.Length;
        for (int i = 0; i < lngt && !buffer.IsFull; i++)
        {
            buffer.Add(value[i]);
        }
        _buffer = buffer;
    }

    public static explicit operator FixedString1024(string value)
    {
        return new FixedString1024(value);
    }

    public static implicit operator string(in FixedString1024 value)
    {
        Span<char> chars = stackalloc char[value._buffer.Count];
        value._buffer.ReadInto(chars);

        return new string(chars);
    }

    public override string ToString() => this;

    public bool Equals(FixedString1024 other)
    {
        Span<char> chars1 = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars1);

        Span<char> chars2 = stackalloc char[other._buffer.Count];
        other._buffer.ReadInto(chars2);

        return chars1.SequenceEqual(chars2);
    }

    public override bool Equals(object? obj)
    {
        return obj is FixedString1024 other && Equals(other);
    }

    public override int GetHashCode()
    {
        Span<char> chars = stackalloc char[_buffer.Count];
        _buffer.ReadInto(chars);

        HashCode hashcode = new();

        hashcode.Add(chars.Length);
        foreach (char c in chars)
        {
            hashcode.Add(c);
        }

        return hashcode.ToHashCode();
    }

    public static bool operator ==(in FixedString1024 left, in FixedString1024 right) => left.Equals(right);
    public static bool operator !=(in FixedString1024 left, in FixedString1024 right) => !left.Equals(right);
}

#endregion