using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

public class SimpleCodeGeneratorWindow : EditorWindow
{
    private class PendingChange
    {
        public string FilePath;
        public string NewContent;
    }

    private List<PendingChange> pendingChanges = new();
    private Vector2 scrollPosition;
    private bool hasScanned = false;

    [MenuItem("Automation/Tools/Regenerate Code")]
    public static void ShowWindow()
    {
        GetWindow<SimpleCodeGeneratorWindow>("CodeGen Preview");
    }

    private void OnGUI()
    {
        GUILayout.Space(10);
        GUILayout.Label("Code Generator - Preview Changes", EditorStyles.boldLabel);
        GUILayout.Space(5);

        if (GUILayout.Button("1. Scan files (.cs)", GUILayout.Height(30)))
        {
            ScanFiles();
        }

        if (hasScanned)
        {
            GUILayout.Space(10);

            if (pendingChanges.Count > 0)
            {
                EditorGUILayout.HelpBox($"Found {pendingChanges.Count} files pending update.", MessageType.Info);

                scrollPosition = GUILayout.BeginScrollView(scrollPosition, "box", GUILayout.ExpandHeight(true));
                foreach (var change in pendingChanges)
                {
                    GUILayout.Label(Path.GetFileName(change.FilePath));
                }
                GUILayout.EndScrollView();

                GUILayout.Space(10);

                GUI.backgroundColor = Color.green;
                if (GUILayout.Button("2. Apply and overwrite files", GUILayout.Height(40)))
                {
                    ApplyChanges();
                }
                GUI.backgroundColor = Color.white;
            }
            else
            {
                EditorGUILayout.HelpBox("All files are up to date. No new changes found to generate.", MessageType.Info);
            }
        }
    }

    private void ScanFiles()
    {
        pendingChanges.Clear();
        string[] allCsFiles = Directory.GetFiles(Application.dataPath, "*.cs", SearchOption.AllDirectories);

        foreach (string filePath in allCsFiles)
        {
            string originalContent = File.ReadAllText(filePath);
            string newContent = GetNewContentIfModified(originalContent);

            if (newContent != null && originalContent != newContent)
            {
                pendingChanges.Add(new PendingChange
                {
                    FilePath = filePath,
                    NewContent = newContent
                });
            }
        }

        hasScanned = true;
    }

    private void ApplyChanges()
    {
        foreach (var change in pendingChanges)
        {
            File.WriteAllText(change.FilePath, change.NewContent);
        }

        Debug.Log($"<color=green>Successfully updated code in {pendingChanges.Count} files.</color>");
        pendingChanges.Clear();
        hasScanned = false;
        AssetDatabase.Refresh();
    }

    private static string GetNewContentIfModified(string originalContent)
    {
        string startMarker = "/*\r\nAUTOGEN BEGIN";
        int startIndex = originalContent.IndexOf(startMarker);

        if (startIndex == -1)
        {
            startMarker = "/*\nAUTOGEN BEGIN";
            startIndex = originalContent.IndexOf(startMarker);
        }

        string endMarker = "AUTOGEN END\r\n*/";
        int endIndex = originalContent.IndexOf(endMarker);

        if (endIndex == -1)
        {
            endMarker = "AUTOGEN END\n*/";
            endIndex = originalContent.IndexOf(endMarker);
        }

        if (startIndex == -1 || endIndex == -1 || startIndex >= endIndex)
        {
            return null;
        }

        int payloadStart = startIndex + startMarker.Length;
        string beforeBlock = originalContent.Substring(0, startIndex);
        string blockContent = originalContent.Substring(startIndex, (endIndex + endMarker.Length) - startIndex);
        string payload = originalContent.Substring(payloadStart, endIndex - payloadStart).Trim();

        string generatedCode = GenerateCodeFromPayload(payload);

        string nl = Environment.NewLine;
        return beforeBlock + blockContent + $"{nl}{nl}// --- AUTOGENERATED CODE BELOW ---{nl}{nl}" + generatedCode;
    }

    private static string GenerateCodeFromPayload(string payload)
    {
        var lines = payload.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);

        var variables = new Dictionary<string, string[]>();
        var templateBuilder = new StringBuilder();

        foreach (var line in lines)
        {
            string trimmed = line.Trim();
            if (trimmed.StartsWith("#") && trimmed.Contains("="))
            {
                var parts = trimmed.Split('=');
                string varName = parts[0].Trim();
                string[] values = parts[1].Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries);
                variables[varName] = values;
            }
            else
            {
                templateBuilder.AppendLine(line);
            }
        }

        string template = templateBuilder.ToString().TrimEnd('\r', '\n');
        List<Dictionary<string, string>> combinations = GetCombinations(variables);

        var finalCode = new StringBuilder();
        for (int i = 0; i < combinations.Count; i++)
        {
            var combo = combinations[i];
            string instanceCode = template;
            foreach (var kvp in combo)
            {
                instanceCode = instanceCode.Replace(kvp.Key, kvp.Value);
            }
            
            finalCode.Append(instanceCode);
            finalCode.AppendLine();
        }

        return finalCode.ToString();
    }

    private static List<Dictionary<string, string>> GetCombinations(Dictionary<string, string[]> variables)
    {
        var result = new List<Dictionary<string, string>>()
        {
            new Dictionary<string, string>()
        };

        foreach (var kvp in variables)
        {
            var nextResult = new List<Dictionary<string, string>>();
            foreach (var dict in result)
            {
                foreach (var val in kvp.Value)
                {
                    var newDict = new Dictionary<string, string>(dict);
                    newDict[kvp.Key] = val;
                    nextResult.Add(newDict);
                }
            }
            result = nextResult;
        }

        return result;
    }
}